### PR TITLE
Upgrade to Ember CLI 3.4

### PR DESCRIPTION
**Pull request by balinterdi**
@igorpreston I've upgraded everything to the latest version, converting the code to JavaScript modules and the new testing API. Two of the tests fail and I'm not sure how to fix them as I'm not sure about the intention behind the `trackLocation` code (more precisely, how setting `watcherId` should work which is where the error comes from):

https://github.com/balinterdi/ember-cli-geo/blob/upgrade-babel/addon/services/geolocation.js#L36-L60

### CODE REVIEW

**Comment by alexmasita** [comment]
Hi @balinterdi, is this repo usable until it is merged?  Currently having issues with module imports using the original.

**Comment by balinterdi** [comment]
No, I don't think it is. You'd have to use my branch:

```js
// package.json
{
  (...)
    "ember-cli-geo": "https://github.com/balinterdi/ember-cli-geo.git#upgrade-babel",
}
```

**Comment by balinterdi** [comment]
@igorpreston I managed to fix one of the tests but the other is giving me trouble. I think it has to do with the setup and teardown of the sinon sandbox, but not sure.

Would you be able to take a look so that this PR can be merged and the add-on can be migrated to using JS modules? Thank you!

**Comment by alexmasita** [comment]
Is this getting closer to being merged?  Thank you.

**Comment by balinterdi** [comment]
@igorpreston Sorry, I'm just looking at this again. Could you cut a new release with this change so that people can reliably use the new version that has this fix (igorpreston/ember-cli-geo is subject to change).

Thank you.

**Pull request merged**
